version: '3.2'
services:
  website:
    build:
      context: .
      target: base
      args:
        - userid=${VETS_FRONTEND_USERID:-1000}
    ports:
      - "3001:3001"
    volumes:
      - ./:/application/
    command: yarn watch --host 0.0.0.0
# A production example

  # production:
  #   build:
  #     context: .
  #     target: production
  #     args:
  #       - userid=${VETS_FRONTEND_USERID:-1000}
  #   ports:
  #     - "3002:80"