version: '3.4'
services:
  postgres:
    image: mdillon/postgis:11-alpine
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-password}"
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
  spruce-challenge-api:
    build:
      context: .
      target: development
      args:
        userid: "${SPRUCE_API_USER_ID}"
    image: "spruce-challenge-api:${DOCKER_IMAGE:-latest}"
    volumes:
      - .:/srv/spruce-challenge-api/src
      - test_bundle:/usr/local/bundle
    environment:
      "Settings.database_url": "postgis://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@${POSTGRES_HOST:-postgres}:${POSTGRES_PORT:-5432}/${POSTGRES_DATABASE:-spruce_challenge}"
      "Settings.test_database_url": "postgis://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@${POSTGRES_HOST:-postgres}:${POSTGRES_PORT:-5432}/${POSTGRES_DATABASE:-spruce_challenge_test}"
      POSTGRES_HOST: "${POSTGRES_HOST:-postgres}"
      POSTGRES_PORT: "${POSTGRES_PORT:-5432}"
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-password}"
      CI: "true"
      RAILS_ENV: test
    depends_on:
      - postgres
    links:
      - postgres
volumes:
  test_bundle:
